"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class ConversionUploadErrorEnum(google.protobuf.message.Message):
    """Proto file describing conversion upload errors.

    Container for enum describing possible conversion upload errors.
    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class _ConversionUploadError:
        ValueType = typing.NewType('ValueType', builtins.int)
        V: typing_extensions.TypeAlias = ValueType
    class _ConversionUploadErrorEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ConversionUploadError.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
        UNSPECIFIED: ConversionUploadErrorEnum.ConversionUploadError.ValueType = ...  # 0
        """Enum unspecified."""

        UNKNOWN: ConversionUploadErrorEnum.ConversionUploadError.ValueType = ...  # 1
        """The received error code is not known in this version."""

        TOO_MANY_CONVERSIONS_IN_REQUEST: ConversionUploadErrorEnum.ConversionUploadError.ValueType = ...  # 2
        """The request contained more than 2000 conversions."""

        UNPARSEABLE_GCLID: ConversionUploadErrorEnum.ConversionUploadError.ValueType = ...  # 3
        """The specified gclid could not be decoded."""

        CONVERSION_PRECEDES_EVENT: ConversionUploadErrorEnum.ConversionUploadError.ValueType = ...  # 42
        """The specified conversion_date_time is before the event time
        associated with the given identifier or iOS URL parameter.
        """

        EXPIRED_EVENT: ConversionUploadErrorEnum.ConversionUploadError.ValueType = ...  # 43
        """The click associated with the given identifier or iOS URL parameter is
        either too old to be imported or occurred outside of the click through
        lookback window for the specified conversion action.
        """

        TOO_RECENT_EVENT: ConversionUploadErrorEnum.ConversionUploadError.ValueType = ...  # 44
        """The click associated with the given identifier or iOS URL parameter
        occurred too recently. Please try uploading again after 6 hours have
        passed since the click occurred.
        """

        EVENT_NOT_FOUND: ConversionUploadErrorEnum.ConversionUploadError.ValueType = ...  # 45
        """The click associated with the given identifier or iOS URL parameter could
        not be found in the system. This can happen if the identifier or iOS URL
        parameter are collected for non Google Ads clicks.
        """

        UNAUTHORIZED_CUSTOMER: ConversionUploadErrorEnum.ConversionUploadError.ValueType = ...  # 8
        """The click associated with the given identifier or iOS URL parameter is
        owned by a customer account that the uploading customer does not manage.
        """

        INVALID_CONVERSION_ACTION: ConversionUploadErrorEnum.ConversionUploadError.ValueType = ...  # 9
        """No upload eligible conversion action that matches the provided
        information can be found for the customer.
        """

        TOO_RECENT_CONVERSION_ACTION: ConversionUploadErrorEnum.ConversionUploadError.ValueType = ...  # 10
        """The specified conversion action was created too recently.
        Please try the upload again after 4-6 hours have passed since the
        conversion action was created.
        """

        CONVERSION_TRACKING_NOT_ENABLED_AT_IMPRESSION_TIME: ConversionUploadErrorEnum.ConversionUploadError.ValueType = ...  # 11
        """The click associated with the given identifier does not contain
        conversion tracking information.
        """

        EXTERNAL_ATTRIBUTION_DATA_SET_FOR_NON_EXTERNALLY_ATTRIBUTED_CONVERSION_ACTION: ConversionUploadErrorEnum.ConversionUploadError.ValueType = ...  # 12
        """The specified conversion action does not use an external attribution
        model, but external_attribution_data was set.
        """

        EXTERNAL_ATTRIBUTION_DATA_NOT_SET_FOR_EXTERNALLY_ATTRIBUTED_CONVERSION_ACTION: ConversionUploadErrorEnum.ConversionUploadError.ValueType = ...  # 13
        """The specified conversion action uses an external attribution model, but
        external_attribution_data or one of its contained fields was not set.
        Both external_attribution_credit and external_attribution_model must be
        set for externally attributed conversion actions.
        """

        ORDER_ID_NOT_PERMITTED_FOR_EXTERNALLY_ATTRIBUTED_CONVERSION_ACTION: ConversionUploadErrorEnum.ConversionUploadError.ValueType = ...  # 14
        """Order IDs are not supported for conversion actions which use an external
        attribution model.
        """

        ORDER_ID_ALREADY_IN_USE: ConversionUploadErrorEnum.ConversionUploadError.ValueType = ...  # 15
        """A conversion with the same order id and conversion action combination
        already exists in our system.
        """

        DUPLICATE_ORDER_ID: ConversionUploadErrorEnum.ConversionUploadError.ValueType = ...  # 16
        """The request contained two or more conversions with the same order id and
        conversion action combination.
        """

        TOO_RECENT_CALL: ConversionUploadErrorEnum.ConversionUploadError.ValueType = ...  # 17
        """The call occurred too recently. Please try uploading again after 12 hours
        have passed since the call occurred.
        """

        EXPIRED_CALL: ConversionUploadErrorEnum.ConversionUploadError.ValueType = ...  # 18
        """The click that initiated the call is too old for this conversion to be
        imported.
        """

        CALL_NOT_FOUND: ConversionUploadErrorEnum.ConversionUploadError.ValueType = ...  # 19
        """The call or the click leading to the call was not found."""

        CONVERSION_PRECEDES_CALL: ConversionUploadErrorEnum.ConversionUploadError.ValueType = ...  # 20
        """The specified conversion_date_time is before the call_start_date_time."""

        CONVERSION_TRACKING_NOT_ENABLED_AT_CALL_TIME: ConversionUploadErrorEnum.ConversionUploadError.ValueType = ...  # 21
        """The click associated with the call does not contain conversion tracking
        information.
        """

        UNPARSEABLE_CALLERS_PHONE_NUMBER: ConversionUploadErrorEnum.ConversionUploadError.ValueType = ...  # 22
        """The callerâ€™s phone number cannot be parsed. It should be formatted either
        as E.164 "+16502531234", International "+64 3-331 6005" or US national
        number "6502531234".
        """

        CLICK_CONVERSION_ALREADY_EXISTS: ConversionUploadErrorEnum.ConversionUploadError.ValueType = ...  # 23
        """A conversion with this timestamp already exists for this click. To upload
        another conversion, please use a different timestamp.
        """

        CALL_CONVERSION_ALREADY_EXISTS: ConversionUploadErrorEnum.ConversionUploadError.ValueType = ...  # 24
        """A conversion with this timestamp already exists for this call. To upload
        another conversion, please use a different timestamp.
        """

        DUPLICATE_CLICK_CONVERSION_IN_REQUEST: ConversionUploadErrorEnum.ConversionUploadError.ValueType = ...  # 25
        """This conversion has the same click and timestamp as another conversion in
        the request. To upload another conversion for this click, please use a
        different timestamp.
        """

        DUPLICATE_CALL_CONVERSION_IN_REQUEST: ConversionUploadErrorEnum.ConversionUploadError.ValueType = ...  # 26
        """This conversion has the same call and timestamp as another conversion in
        the request. To upload another conversion for this call, please use a
        different timestamp.
        """

        CUSTOM_VARIABLE_NOT_ENABLED: ConversionUploadErrorEnum.ConversionUploadError.ValueType = ...  # 28
        """The custom variable is not enabled."""

        CUSTOM_VARIABLE_VALUE_CONTAINS_PII: ConversionUploadErrorEnum.ConversionUploadError.ValueType = ...  # 29
        """The value of the custom variable contains private customer data, such
        as email addresses or phone numbers.
        """

        INVALID_CUSTOMER_FOR_CLICK: ConversionUploadErrorEnum.ConversionUploadError.ValueType = ...  # 30
        """The click associated with the given identifier or iOS URL parameter isn't
        from the account where conversion tracking is set up.
        """

        INVALID_CUSTOMER_FOR_CALL: ConversionUploadErrorEnum.ConversionUploadError.ValueType = ...  # 31
        """The click associated with the given call isn't from the account where
        conversion tracking is set up.
        """

        CONVERSION_NOT_COMPLIANT_WITH_ATT_POLICY: ConversionUploadErrorEnum.ConversionUploadError.ValueType = ...  # 32
        """The conversion can't be uploaded because the conversion source didn't
        comply with the App Tracking Transparency (ATT) policy or the person who
        converted didn't consent to tracking.
        """

        CLICK_NOT_FOUND: ConversionUploadErrorEnum.ConversionUploadError.ValueType = ...  # 33
        """No click was found for the provided user identifiers that could be
        applied to the specified conversion action.
        """

        INVALID_USER_IDENTIFIER: ConversionUploadErrorEnum.ConversionUploadError.ValueType = ...  # 34
        """The provided user identifier is not a SHA-256 hash. It is either unhashed
        or hashed using a different hash function.
        """

        EXTERNALLY_ATTRIBUTED_CONVERSION_ACTION_NOT_PERMITTED_WITH_USER_IDENTIFIER: ConversionUploadErrorEnum.ConversionUploadError.ValueType = ...  # 35
        """Conversion actions which use an external attribution model cannot be used
        with UserIdentifier.
        """

        UNSUPPORTED_USER_IDENTIFIER: ConversionUploadErrorEnum.ConversionUploadError.ValueType = ...  # 36
        """The provided user identifier is not supported. ConversionUploadService
        only supports hashed_email and hashed_phone_number.
        """

        GBRAID_WBRAID_BOTH_SET: ConversionUploadErrorEnum.ConversionUploadError.ValueType = ...  # 38
        """gbraid and wbraid are both set in the request. Only one is allowed."""

        UNPARSEABLE_WBRAID: ConversionUploadErrorEnum.ConversionUploadError.ValueType = ...  # 39
        """The specified wbraid could not be decoded."""

        UNPARSEABLE_GBRAID: ConversionUploadErrorEnum.ConversionUploadError.ValueType = ...  # 40
        """The specified gbraid could not be decoded."""

        EXTERNALLY_ATTRIBUTED_CONVERSION_TYPE_NOT_PERMITTED_WITH_BRAID: ConversionUploadErrorEnum.ConversionUploadError.ValueType = ...  # 41
        """Conversion types which use an external attribution model cannot be used
        with gbraid or wbraid.
        """

        ONE_PER_CLICK_CONVERSION_ACTION_NOT_PERMITTED_WITH_BRAID: ConversionUploadErrorEnum.ConversionUploadError.ValueType = ...  # 46
        """Conversion actions which use the one-per-click counting type cannot be
        used with gbraid or wbraid.
        """

    class ConversionUploadError(_ConversionUploadError, metaclass=_ConversionUploadErrorEnumTypeWrapper):
        """Enum describing possible conversion upload errors."""
        pass

    UNSPECIFIED: ConversionUploadErrorEnum.ConversionUploadError.ValueType = ...  # 0
    """Enum unspecified."""

    UNKNOWN: ConversionUploadErrorEnum.ConversionUploadError.ValueType = ...  # 1
    """The received error code is not known in this version."""

    TOO_MANY_CONVERSIONS_IN_REQUEST: ConversionUploadErrorEnum.ConversionUploadError.ValueType = ...  # 2
    """The request contained more than 2000 conversions."""

    UNPARSEABLE_GCLID: ConversionUploadErrorEnum.ConversionUploadError.ValueType = ...  # 3
    """The specified gclid could not be decoded."""

    CONVERSION_PRECEDES_EVENT: ConversionUploadErrorEnum.ConversionUploadError.ValueType = ...  # 42
    """The specified conversion_date_time is before the event time
    associated with the given identifier or iOS URL parameter.
    """

    EXPIRED_EVENT: ConversionUploadErrorEnum.ConversionUploadError.ValueType = ...  # 43
    """The click associated with the given identifier or iOS URL parameter is
    either too old to be imported or occurred outside of the click through
    lookback window for the specified conversion action.
    """

    TOO_RECENT_EVENT: ConversionUploadErrorEnum.ConversionUploadError.ValueType = ...  # 44
    """The click associated with the given identifier or iOS URL parameter
    occurred too recently. Please try uploading again after 6 hours have
    passed since the click occurred.
    """

    EVENT_NOT_FOUND: ConversionUploadErrorEnum.ConversionUploadError.ValueType = ...  # 45
    """The click associated with the given identifier or iOS URL parameter could
    not be found in the system. This can happen if the identifier or iOS URL
    parameter are collected for non Google Ads clicks.
    """

    UNAUTHORIZED_CUSTOMER: ConversionUploadErrorEnum.ConversionUploadError.ValueType = ...  # 8
    """The click associated with the given identifier or iOS URL parameter is
    owned by a customer account that the uploading customer does not manage.
    """

    INVALID_CONVERSION_ACTION: ConversionUploadErrorEnum.ConversionUploadError.ValueType = ...  # 9
    """No upload eligible conversion action that matches the provided
    information can be found for the customer.
    """

    TOO_RECENT_CONVERSION_ACTION: ConversionUploadErrorEnum.ConversionUploadError.ValueType = ...  # 10
    """The specified conversion action was created too recently.
    Please try the upload again after 4-6 hours have passed since the
    conversion action was created.
    """

    CONVERSION_TRACKING_NOT_ENABLED_AT_IMPRESSION_TIME: ConversionUploadErrorEnum.ConversionUploadError.ValueType = ...  # 11
    """The click associated with the given identifier does not contain
    conversion tracking information.
    """

    EXTERNAL_ATTRIBUTION_DATA_SET_FOR_NON_EXTERNALLY_ATTRIBUTED_CONVERSION_ACTION: ConversionUploadErrorEnum.ConversionUploadError.ValueType = ...  # 12
    """The specified conversion action does not use an external attribution
    model, but external_attribution_data was set.
    """

    EXTERNAL_ATTRIBUTION_DATA_NOT_SET_FOR_EXTERNALLY_ATTRIBUTED_CONVERSION_ACTION: ConversionUploadErrorEnum.ConversionUploadError.ValueType = ...  # 13
    """The specified conversion action uses an external attribution model, but
    external_attribution_data or one of its contained fields was not set.
    Both external_attribution_credit and external_attribution_model must be
    set for externally attributed conversion actions.
    """

    ORDER_ID_NOT_PERMITTED_FOR_EXTERNALLY_ATTRIBUTED_CONVERSION_ACTION: ConversionUploadErrorEnum.ConversionUploadError.ValueType = ...  # 14
    """Order IDs are not supported for conversion actions which use an external
    attribution model.
    """

    ORDER_ID_ALREADY_IN_USE: ConversionUploadErrorEnum.ConversionUploadError.ValueType = ...  # 15
    """A conversion with the same order id and conversion action combination
    already exists in our system.
    """

    DUPLICATE_ORDER_ID: ConversionUploadErrorEnum.ConversionUploadError.ValueType = ...  # 16
    """The request contained two or more conversions with the same order id and
    conversion action combination.
    """

    TOO_RECENT_CALL: ConversionUploadErrorEnum.ConversionUploadError.ValueType = ...  # 17
    """The call occurred too recently. Please try uploading again after 12 hours
    have passed since the call occurred.
    """

    EXPIRED_CALL: ConversionUploadErrorEnum.ConversionUploadError.ValueType = ...  # 18
    """The click that initiated the call is too old for this conversion to be
    imported.
    """

    CALL_NOT_FOUND: ConversionUploadErrorEnum.ConversionUploadError.ValueType = ...  # 19
    """The call or the click leading to the call was not found."""

    CONVERSION_PRECEDES_CALL: ConversionUploadErrorEnum.ConversionUploadError.ValueType = ...  # 20
    """The specified conversion_date_time is before the call_start_date_time."""

    CONVERSION_TRACKING_NOT_ENABLED_AT_CALL_TIME: ConversionUploadErrorEnum.ConversionUploadError.ValueType = ...  # 21
    """The click associated with the call does not contain conversion tracking
    information.
    """

    UNPARSEABLE_CALLERS_PHONE_NUMBER: ConversionUploadErrorEnum.ConversionUploadError.ValueType = ...  # 22
    """The callerâ€™s phone number cannot be parsed. It should be formatted either
    as E.164 "+16502531234", International "+64 3-331 6005" or US national
    number "6502531234".
    """

    CLICK_CONVERSION_ALREADY_EXISTS: ConversionUploadErrorEnum.ConversionUploadError.ValueType = ...  # 23
    """A conversion with this timestamp already exists for this click. To upload
    another conversion, please use a different timestamp.
    """

    CALL_CONVERSION_ALREADY_EXISTS: ConversionUploadErrorEnum.ConversionUploadError.ValueType = ...  # 24
    """A conversion with this timestamp already exists for this call. To upload
    another conversion, please use a different timestamp.
    """

    DUPLICATE_CLICK_CONVERSION_IN_REQUEST: ConversionUploadErrorEnum.ConversionUploadError.ValueType = ...  # 25
    """This conversion has the same click and timestamp as another conversion in
    the request. To upload another conversion for this click, please use a
    different timestamp.
    """

    DUPLICATE_CALL_CONVERSION_IN_REQUEST: ConversionUploadErrorEnum.ConversionUploadError.ValueType = ...  # 26
    """This conversion has the same call and timestamp as another conversion in
    the request. To upload another conversion for this call, please use a
    different timestamp.
    """

    CUSTOM_VARIABLE_NOT_ENABLED: ConversionUploadErrorEnum.ConversionUploadError.ValueType = ...  # 28
    """The custom variable is not enabled."""

    CUSTOM_VARIABLE_VALUE_CONTAINS_PII: ConversionUploadErrorEnum.ConversionUploadError.ValueType = ...  # 29
    """The value of the custom variable contains private customer data, such
    as email addresses or phone numbers.
    """

    INVALID_CUSTOMER_FOR_CLICK: ConversionUploadErrorEnum.ConversionUploadError.ValueType = ...  # 30
    """The click associated with the given identifier or iOS URL parameter isn't
    from the account where conversion tracking is set up.
    """

    INVALID_CUSTOMER_FOR_CALL: ConversionUploadErrorEnum.ConversionUploadError.ValueType = ...  # 31
    """The click associated with the given call isn't from the account where
    conversion tracking is set up.
    """

    CONVERSION_NOT_COMPLIANT_WITH_ATT_POLICY: ConversionUploadErrorEnum.ConversionUploadError.ValueType = ...  # 32
    """The conversion can't be uploaded because the conversion source didn't
    comply with the App Tracking Transparency (ATT) policy or the person who
    converted didn't consent to tracking.
    """

    CLICK_NOT_FOUND: ConversionUploadErrorEnum.ConversionUploadError.ValueType = ...  # 33
    """No click was found for the provided user identifiers that could be
    applied to the specified conversion action.
    """

    INVALID_USER_IDENTIFIER: ConversionUploadErrorEnum.ConversionUploadError.ValueType = ...  # 34
    """The provided user identifier is not a SHA-256 hash. It is either unhashed
    or hashed using a different hash function.
    """

    EXTERNALLY_ATTRIBUTED_CONVERSION_ACTION_NOT_PERMITTED_WITH_USER_IDENTIFIER: ConversionUploadErrorEnum.ConversionUploadError.ValueType = ...  # 35
    """Conversion actions which use an external attribution model cannot be used
    with UserIdentifier.
    """

    UNSUPPORTED_USER_IDENTIFIER: ConversionUploadErrorEnum.ConversionUploadError.ValueType = ...  # 36
    """The provided user identifier is not supported. ConversionUploadService
    only supports hashed_email and hashed_phone_number.
    """

    GBRAID_WBRAID_BOTH_SET: ConversionUploadErrorEnum.ConversionUploadError.ValueType = ...  # 38
    """gbraid and wbraid are both set in the request. Only one is allowed."""

    UNPARSEABLE_WBRAID: ConversionUploadErrorEnum.ConversionUploadError.ValueType = ...  # 39
    """The specified wbraid could not be decoded."""

    UNPARSEABLE_GBRAID: ConversionUploadErrorEnum.ConversionUploadError.ValueType = ...  # 40
    """The specified gbraid could not be decoded."""

    EXTERNALLY_ATTRIBUTED_CONVERSION_TYPE_NOT_PERMITTED_WITH_BRAID: ConversionUploadErrorEnum.ConversionUploadError.ValueType = ...  # 41
    """Conversion types which use an external attribution model cannot be used
    with gbraid or wbraid.
    """

    ONE_PER_CLICK_CONVERSION_ACTION_NOT_PERMITTED_WITH_BRAID: ConversionUploadErrorEnum.ConversionUploadError.ValueType = ...  # 46
    """Conversion actions which use the one-per-click counting type cannot be
    used with gbraid or wbraid.
    """


    def __init__(self,
        ) -> None: ...
global___ConversionUploadErrorEnum = ConversionUploadErrorEnum
