"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class DatabaseErrorEnum(google.protobuf.message.Message):
    """Proto file describing database errors.

    Container for enum describing possible database errors.
    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class _DatabaseError:
        ValueType = typing.NewType('ValueType', builtins.int)
        V: typing_extensions.TypeAlias = ValueType
    class _DatabaseErrorEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_DatabaseError.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
        UNSPECIFIED: DatabaseErrorEnum.DatabaseError.ValueType = ...  # 0
        """Enum unspecified."""

        UNKNOWN: DatabaseErrorEnum.DatabaseError.ValueType = ...  # 1
        """The received error code is not known in this version."""

        CONCURRENT_MODIFICATION: DatabaseErrorEnum.DatabaseError.ValueType = ...  # 2
        """Multiple requests were attempting to modify the same resource at once.
        Please retry the request.
        """

        DATA_CONSTRAINT_VIOLATION: DatabaseErrorEnum.DatabaseError.ValueType = ...  # 3
        """The request conflicted with existing data. This error will usually be
        replaced with a more specific error if the request is retried.
        """

        REQUEST_TOO_LARGE: DatabaseErrorEnum.DatabaseError.ValueType = ...  # 4
        """The data written is too large. Please split the request into smaller
        requests.
        """

    class DatabaseError(_DatabaseError, metaclass=_DatabaseErrorEnumTypeWrapper):
        """Enum describing possible database errors."""
        pass

    UNSPECIFIED: DatabaseErrorEnum.DatabaseError.ValueType = ...  # 0
    """Enum unspecified."""

    UNKNOWN: DatabaseErrorEnum.DatabaseError.ValueType = ...  # 1
    """The received error code is not known in this version."""

    CONCURRENT_MODIFICATION: DatabaseErrorEnum.DatabaseError.ValueType = ...  # 2
    """Multiple requests were attempting to modify the same resource at once.
    Please retry the request.
    """

    DATA_CONSTRAINT_VIOLATION: DatabaseErrorEnum.DatabaseError.ValueType = ...  # 3
    """The request conflicted with existing data. This error will usually be
    replaced with a more specific error if the request is retried.
    """

    REQUEST_TOO_LARGE: DatabaseErrorEnum.DatabaseError.ValueType = ...  # 4
    """The data written is too large. Please split the request into smaller
    requests.
    """


    def __init__(self,
        ) -> None: ...
global___DatabaseErrorEnum = DatabaseErrorEnum
