"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class MutateErrorEnum(google.protobuf.message.Message):
    """Proto file describing mutate errors.

    Container for enum describing possible mutate errors.
    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class _MutateError:
        ValueType = typing.NewType('ValueType', builtins.int)
        V: typing_extensions.TypeAlias = ValueType
    class _MutateErrorEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_MutateError.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
        UNSPECIFIED: MutateErrorEnum.MutateError.ValueType = ...  # 0
        """Enum unspecified."""

        UNKNOWN: MutateErrorEnum.MutateError.ValueType = ...  # 1
        """The received error code is not known in this version."""

        RESOURCE_NOT_FOUND: MutateErrorEnum.MutateError.ValueType = ...  # 3
        """Requested resource was not found."""

        ID_EXISTS_IN_MULTIPLE_MUTATES: MutateErrorEnum.MutateError.ValueType = ...  # 7
        """Cannot mutate the same resource twice in one request."""

        INCONSISTENT_FIELD_VALUES: MutateErrorEnum.MutateError.ValueType = ...  # 8
        """The field's contents don't match another field that represents the same
        data.
        """

        MUTATE_NOT_ALLOWED: MutateErrorEnum.MutateError.ValueType = ...  # 9
        """Mutates are not allowed for the requested resource."""

        RESOURCE_NOT_IN_GOOGLE_ADS: MutateErrorEnum.MutateError.ValueType = ...  # 10
        """The resource isn't in Google Ads. It belongs to another ads system."""

        RESOURCE_ALREADY_EXISTS: MutateErrorEnum.MutateError.ValueType = ...  # 11
        """The resource being created already exists."""

        RESOURCE_DOES_NOT_SUPPORT_VALIDATE_ONLY: MutateErrorEnum.MutateError.ValueType = ...  # 12
        """This resource cannot be used with "validate_only"."""

        RESOURCE_READ_ONLY: MutateErrorEnum.MutateError.ValueType = ...  # 13
        """Attempt to write to read-only fields."""

    class MutateError(_MutateError, metaclass=_MutateErrorEnumTypeWrapper):
        """Enum describing possible mutate errors."""
        pass

    UNSPECIFIED: MutateErrorEnum.MutateError.ValueType = ...  # 0
    """Enum unspecified."""

    UNKNOWN: MutateErrorEnum.MutateError.ValueType = ...  # 1
    """The received error code is not known in this version."""

    RESOURCE_NOT_FOUND: MutateErrorEnum.MutateError.ValueType = ...  # 3
    """Requested resource was not found."""

    ID_EXISTS_IN_MULTIPLE_MUTATES: MutateErrorEnum.MutateError.ValueType = ...  # 7
    """Cannot mutate the same resource twice in one request."""

    INCONSISTENT_FIELD_VALUES: MutateErrorEnum.MutateError.ValueType = ...  # 8
    """The field's contents don't match another field that represents the same
    data.
    """

    MUTATE_NOT_ALLOWED: MutateErrorEnum.MutateError.ValueType = ...  # 9
    """Mutates are not allowed for the requested resource."""

    RESOURCE_NOT_IN_GOOGLE_ADS: MutateErrorEnum.MutateError.ValueType = ...  # 10
    """The resource isn't in Google Ads. It belongs to another ads system."""

    RESOURCE_ALREADY_EXISTS: MutateErrorEnum.MutateError.ValueType = ...  # 11
    """The resource being created already exists."""

    RESOURCE_DOES_NOT_SUPPORT_VALIDATE_ONLY: MutateErrorEnum.MutateError.ValueType = ...  # 12
    """This resource cannot be used with "validate_only"."""

    RESOURCE_READ_ONLY: MutateErrorEnum.MutateError.ValueType = ...  # 13
    """Attempt to write to read-only fields."""


    def __init__(self,
        ) -> None: ...
global___MutateErrorEnum = MutateErrorEnum
