"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class SharedSetErrorEnum(google.protobuf.message.Message):
    """Proto file describing shared set errors.

    Container for enum describing possible shared set errors.
    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class _SharedSetError:
        ValueType = typing.NewType('ValueType', builtins.int)
        V: typing_extensions.TypeAlias = ValueType
    class _SharedSetErrorEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_SharedSetError.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
        UNSPECIFIED: SharedSetErrorEnum.SharedSetError.ValueType = ...  # 0
        """Enum unspecified."""

        UNKNOWN: SharedSetErrorEnum.SharedSetError.ValueType = ...  # 1
        """The received error code is not known in this version."""

        CUSTOMER_CANNOT_CREATE_SHARED_SET_OF_THIS_TYPE: SharedSetErrorEnum.SharedSetError.ValueType = ...  # 2
        """The customer cannot create this type of shared set."""

        DUPLICATE_NAME: SharedSetErrorEnum.SharedSetError.ValueType = ...  # 3
        """A shared set with this name already exists."""

        SHARED_SET_REMOVED: SharedSetErrorEnum.SharedSetError.ValueType = ...  # 4
        """Removed shared sets cannot be mutated."""

        SHARED_SET_IN_USE: SharedSetErrorEnum.SharedSetError.ValueType = ...  # 5
        """The shared set cannot be removed because it is in use."""

    class SharedSetError(_SharedSetError, metaclass=_SharedSetErrorEnumTypeWrapper):
        """Enum describing possible shared set errors."""
        pass

    UNSPECIFIED: SharedSetErrorEnum.SharedSetError.ValueType = ...  # 0
    """Enum unspecified."""

    UNKNOWN: SharedSetErrorEnum.SharedSetError.ValueType = ...  # 1
    """The received error code is not known in this version."""

    CUSTOMER_CANNOT_CREATE_SHARED_SET_OF_THIS_TYPE: SharedSetErrorEnum.SharedSetError.ValueType = ...  # 2
    """The customer cannot create this type of shared set."""

    DUPLICATE_NAME: SharedSetErrorEnum.SharedSetError.ValueType = ...  # 3
    """A shared set with this name already exists."""

    SHARED_SET_REMOVED: SharedSetErrorEnum.SharedSetError.ValueType = ...  # 4
    """Removed shared sets cannot be mutated."""

    SHARED_SET_IN_USE: SharedSetErrorEnum.SharedSetError.ValueType = ...  # 5
    """The shared set cannot be removed because it is in use."""


    def __init__(self,
        ) -> None: ...
global___SharedSetErrorEnum = SharedSetErrorEnum
