Traceback (most recent call last):
  File "/home/runner/.cache/pypoetry/virtualenvs/viam-sdk-kW_PCoAn-py3.12/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/runner/.cache/pypoetry/virtualenvs/viam-sdk-kW_PCoAn-py3.12/lib/python3.12/site-packages/nbclient/client.py", line 1269, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/viam-sdk-kW_PCoAn-py3.12/lib/python3.12/site-packages/nbclient/util.py", line 85, in wrapped
    return just_run(coro(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/viam-sdk-kW_PCoAn-py3.12/lib/python3.12/site-packages/nbclient/util.py", line 60, in just_run
    return loop.run_until_complete(coro)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.6/x64/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/viam-sdk-kW_PCoAn-py3.12/lib/python3.12/site-packages/nbclient/client.py", line 707, in async_execute
    await self.async_execute_cell(
  File "/home/runner/.cache/pypoetry/virtualenvs/viam-sdk-kW_PCoAn-py3.12/lib/python3.12/site-packages/nbclient/client.py", line 1025, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/runner/.cache/pypoetry/virtualenvs/viam-sdk-kW_PCoAn-py3.12/lib/python3.12/site-packages/nbclient/client.py", line 919, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from datetime import datetime
from viam.utils import create_filter

left_motor_filter = create_filter(
    component_name="left_motor", start_time=datetime(2023, 6, 5, 11), end_time=datetime(2023, 6, 5, 13, 30), tags=["speed_test_run"]
)

data = await data_client.tabular_data_by_filter(filter=left_motor_filter)
for tab in data:
    print(tab)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mOSError[0m                                   Traceback (most recent call last)
Cell [0;32mIn[14], line 8[0m
[1;32m      2[0m [38;5;28;01mfrom[39;00m [38;5;21;01mviam[39;00m[38;5;21;01m.[39;00m[38;5;21;01mutils[39;00m [38;5;28;01mimport[39;00m create_filter
[1;32m      4[0m left_motor_filter [38;5;241m=[39m create_filter(
[1;32m      5[0m     component_name[38;5;241m=[39m[38;5;124m"[39m[38;5;124mleft_motor[39m[38;5;124m"[39m, start_time[38;5;241m=[39mdatetime([38;5;241m2023[39m, [38;5;241m6[39m, [38;5;241m5[39m, [38;5;241m11[39m), end_time[38;5;241m=[39mdatetime([38;5;241m2023[39m, [38;5;241m6[39m, [38;5;241m5[39m, [38;5;241m13[39m, [38;5;241m30[39m), tags[38;5;241m=[39m[[38;5;124m"[39m[38;5;124mspeed_test_run[39m[38;5;124m"[39m]
[1;32m      6[0m )
[0;32m----> 8[0m data [38;5;241m=[39m [38;5;28;01mawait[39;00m data_client[38;5;241m.[39mtabular_data_by_filter([38;5;28mfilter[39m[38;5;241m=[39mleft_motor_filter)
[1;32m      9[0m [38;5;28;01mfor[39;00m tab [38;5;129;01min[39;00m data:
[1;32m     10[0m     [38;5;28mprint[39m(tab)

File [0;32m~/work/viam-python-sdk/viam-python-sdk/src/viam/app/data_client.py:222[0m, in [0;36mDataClient.tabular_data_by_filter[0;34m(self, filter, limit, sort_order, last, count_only, include_internal_data, dest)[0m
[1;32m    220[0m     data_request[38;5;241m.[39mlast [38;5;241m=[39m last
[1;32m    221[0m request [38;5;241m=[39m TabularDataByFilterRequest(data_request[38;5;241m=[39mdata_request, count_only[38;5;241m=[39mcount_only, include_internal_data[38;5;241m=[39minclude_internal_data)
[0;32m--> 222[0m response: TabularDataByFilterResponse [38;5;241m=[39m [38;5;28;01mawait[39;00m [38;5;28mself[39m[38;5;241m.[39m_data_client[38;5;241m.[39mTabularDataByFilter(request, metadata[38;5;241m=[39m[38;5;28mself[39m[38;5;241m.[39m_metadata)
[1;32m    223[0m data [38;5;241m=[39m [
[1;32m    224[0m     DataClient[38;5;241m.[39mTabularData(
[1;32m    225[0m         struct_to_dict(struct[38;5;241m.[39mdata),
[0;32m   (...)[0m
[1;32m    230[0m     [38;5;28;01mfor[39;00m struct [38;5;129;01min[39;00m response[38;5;241m.[39mdata
[1;32m    231[0m ]
[1;32m    233[0m [38;5;28;01mif[39;00m dest:

File [0;32m~/.cache/pypoetry/virtualenvs/viam-sdk-kW_PCoAn-py3.12/lib/python3.12/site-packages/grpclib/client.py:903[0m, in [0;36mUnaryUnaryMethod.__call__[0;34m(self, message, timeout, metadata)[0m
[1;32m    895[0m [38;5;250m[39m[38;5;124;03m"""Coroutine to perform defined call.[39;00m
[1;32m    896[0m 
[1;32m    897[0m [38;5;124;03m:param message: message[39;00m
[0;32m   (...)[0m
[1;32m    900[0m [38;5;124;03m:return: message[39;00m
[1;32m    901[0m [38;5;124;03m"""[39;00m
[1;32m    902[0m [38;5;28;01masync[39;00m [38;5;28;01mwith[39;00m [38;5;28mself[39m[38;5;241m.[39mopen(timeout[38;5;241m=[39mtimeout, metadata[38;5;241m=[39mmetadata) [38;5;28;01mas[39;00m stream:
[0;32m--> 903[0m     [38;5;28;01mawait[39;00m stream[38;5;241m.[39msend_message(message, end[38;5;241m=[39m[38;5;28;01mTrue[39;00m)
[1;32m    904[0m     reply [38;5;241m=[39m [38;5;28;01mawait[39;00m stream[38;5;241m.[39mrecv_message()
[1;32m    905[0m [38;5;28;01massert[39;00m reply [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m

File [0;32m~/.cache/pypoetry/virtualenvs/viam-sdk-kW_PCoAn-py3.12/lib/python3.12/site-packages/grpclib/client.py:241[0m, in [0;36mStream.send_message[0;34m(self, message, end)[0m
[1;32m    221[0m [38;5;250m[39m[38;5;124;03m"""Coroutine to send message to the server.[39;00m
[1;32m    222[0m 
[1;32m    223[0m [38;5;124;03mIf client sends UNARY request, then you should call this coroutine only[39;00m
[0;32m   (...)[0m
[1;32m    238[0m [38;5;124;03madditional HTTP/2 frame.[39;00m
[1;32m    239[0m [38;5;124;03m"""[39;00m
[1;32m    240[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m [38;5;28mself[39m[38;5;241m.[39m_send_request_done:
[0;32m--> 241[0m     [38;5;28;01mawait[39;00m [38;5;28mself[39m[38;5;241m.[39msend_request()
[1;32m    243[0m end_stream [38;5;241m=[39m end
[1;32m    244[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m [38;5;28mself[39m[38;5;241m.[39m_cardinality[38;5;241m.[39mclient_streaming:

File [0;32m~/.cache/pypoetry/virtualenvs/viam-sdk-kW_PCoAn-py3.12/lib/python3.12/site-packages/grpclib/client.py:173[0m, in [0;36mStream.send_request[0;34m(self, end)[0m
[1;32m    169[0m     [38;5;28;01mraise[39;00m ProtocolError([38;5;124m'[39m[38;5;124mUnary request requires a message to be sent [39m[38;5;124m'[39m
[1;32m    170[0m                         [38;5;124m'[39m[38;5;124mbefore ending outgoing stream[39m[38;5;124m'[39m)
[1;32m    172[0m [38;5;28;01mwith[39;00m [38;5;28mself[39m[38;5;241m.[39m_wrapper:
[0;32m--> 173[0m     protocol [38;5;241m=[39m [38;5;28;01mawait[39;00m [38;5;28mself[39m[38;5;241m.[39m_channel[38;5;241m.[39m__connect__()
[1;32m    174[0m     stream [38;5;241m=[39m protocol[38;5;241m.[39mprocessor[38;5;241m.[39mconnection\
[1;32m    175[0m         [38;5;241m.[39mcreate_stream(wrapper[38;5;241m=[39m[38;5;28mself[39m[38;5;241m.[39m_wrapper)
[1;32m    177[0m     headers [38;5;241m=[39m [
[1;32m    178[0m         ([38;5;124m'[39m[38;5;124m:method[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mPOST[39m[38;5;124m'[39m),
[1;32m    179[0m         ([38;5;124m'[39m[38;5;124m:scheme[39m[38;5;124m'[39m, [38;5;28mself[39m[38;5;241m.[39m_channel[38;5;241m.[39m_scheme),
[1;32m    180[0m         ([38;5;124m'[39m[38;5;124m:path[39m[38;5;124m'[39m, [38;5;28mself[39m[38;5;241m.[39m_method_name),
[1;32m    181[0m         ([38;5;124m'[39m[38;5;124m:authority[39m[38;5;124m'[39m, [38;5;28mself[39m[38;5;241m.[39m_channel[38;5;241m.[39m_authority),
[1;32m    182[0m     ]

File [0;32m~/.cache/pypoetry/virtualenvs/viam-sdk-kW_PCoAn-py3.12/lib/python3.12/site-packages/grpclib/client.py:748[0m, in [0;36mChannel.__connect__[0;34m(self)[0m
[1;32m    746[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m [38;5;28mself[39m[38;5;241m.[39m_connected:
[1;32m    747[0m     [38;5;28;01mtry[39;00m:
[0;32m--> 748[0m         [38;5;28mself[39m[38;5;241m.[39m_protocol [38;5;241m=[39m [38;5;28;01mawait[39;00m [38;5;28mself[39m[38;5;241m.[39m_create_connection()
[1;32m    749[0m     [38;5;28;01mexcept[39;00m [38;5;167;01mException[39;00m:
[1;32m    750[0m         [38;5;28mself[39m[38;5;241m.[39m_state [38;5;241m=[39m _ChannelState[38;5;241m.[39mTRANSIENT_FAILURE

File [0;32m~/.cache/pypoetry/virtualenvs/viam-sdk-kW_PCoAn-py3.12/lib/python3.12/site-packages/grpclib/client.py:725[0m, in [0;36mChannel._create_connection[0;34m(self)[0m
[1;32m    715[0m     _, protocol [38;5;241m=[39m [38;5;28;01mawait[39;00m [38;5;28mself[39m[38;5;241m.[39m_loop[38;5;241m.[39mcreate_unix_connection(
[1;32m    716[0m         [38;5;28mself[39m[38;5;241m.[39m_protocol_factory,
[1;32m    717[0m         [38;5;28mself[39m[38;5;241m.[39m_path,
[0;32m   (...)[0m
[1;32m    722[0m         ),
[1;32m    723[0m     )
[1;32m    724[0m [38;5;28;01melse[39;00m:
[0;32m--> 725[0m     _, protocol [38;5;241m=[39m [38;5;28;01mawait[39;00m [38;5;28mself[39m[38;5;241m.[39m_loop[38;5;241m.[39mcreate_connection(
[1;32m    726[0m         [38;5;28mself[39m[38;5;241m.[39m_protocol_factory,
[1;32m    727[0m         [38;5;28mself[39m[38;5;241m.[39m_host,
[1;32m    728[0m         [38;5;28mself[39m[38;5;241m.[39m_port,
[1;32m    729[0m         ssl[38;5;241m=[39m[38;5;28mself[39m[38;5;241m.[39m_ssl,
[1;32m    730[0m         server_hostname[38;5;241m=[39m(
[1;32m    731[0m             [38;5;28mself[39m[38;5;241m.[39m_config[38;5;241m.[39mssl_target_name_override
[1;32m    732[0m             [38;5;28;01mif[39;00m [38;5;28mself[39m[38;5;241m.[39m_ssl [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m [38;5;28;01melse[39;00m [38;5;28;01mNone[39;00m
[1;32m    733[0m         ),
[1;32m    734[0m     )
[1;32m    735[0m [38;5;28;01mreturn[39;00m protocol

File [0;32m/opt/hostedtoolcache/Python/3.12.6/x64/lib/python3.12/asyncio/base_events.py:1129[0m, in [0;36mBaseEventLoop.create_connection[0;34m(self, protocol_factory, host, port, ssl, family, proto, flags, sock, local_addr, server_hostname, ssl_handshake_timeout, ssl_shutdown_timeout, happy_eyeballs_delay, interleave, all_errors)[0m
[1;32m   1126[0m             [38;5;28;01mraise[39;00m exceptions[[38;5;241m0[39m]
[1;32m   1127[0m         [38;5;66;03m# Raise a combined exception so the user can see all[39;00m
[1;32m   1128[0m         [38;5;66;03m# the various error messages.[39;00m
[0;32m-> 1129[0m         [38;5;28;01mraise[39;00m [38;5;167;01mOSError[39;00m([38;5;124m'[39m[38;5;124mMultiple exceptions: [39m[38;5;132;01m{}[39;00m[38;5;124m'[39m[38;5;241m.[39mformat(
[1;32m   1130[0m             [38;5;124m'[39m[38;5;124m, [39m[38;5;124m'[39m[38;5;241m.[39mjoin([38;5;28mstr[39m(exc) [38;5;28;01mfor[39;00m exc [38;5;129;01min[39;00m exceptions)))
[1;32m   1131[0m [38;5;28;01mfinally[39;00m:
[1;32m   1132[0m     exceptions [38;5;241m=[39m [38;5;28;01mNone[39;00m

[0;31mOSError[0m: Multiple exceptions: [Errno 111] Connect call failed ('::1', 9092, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 9092)
OSError: Multiple exceptions: [Errno 111] Connect call failed ('::1', 9092, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 9092)

